coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        flags:
          - unit
        if_not_found: error
        if_ci_failed: error
        informational: false
        only_pulls: true